<?php

use Magento\Framework\App\Request\Http;

/** @var \Alex\Fin\Block\TabletsCases $block */
/** @var Http $request */
$request = $this->getRequest();
$caseSku = (int)$request->getParam('casesku');
$idVerified = $block->getCasePresent($caseSku);
?>

<?php if ($idVerified): ?>
    <h2>Delete the record <?= $caseSku ?></h2>
    <form action="<?= $block->getDeleteCaseAction(); ?>" method="post">
        <h5 class="message"><?= __("Are you SURE?") ?></h5>
        <input name="case_sku" type="hidden" value="<?= $caseSku ?>">
        <input type="submit" value="Press to delete the case">
    </form>
<?php else: ?>
    <h5 class="message"><?= __("Invalid link! Please go to the home page and try again!") ?></h5>
    <a class="show" href=" <?= $block->getUrl('fin_route/index/cases/forTabSKU/0') ?>">
        <?= __("Show All avaible Cases (for ALL tablets!) ->") ?>
    </a>
    <br>
    <br>
    <a class="go_back" href=" <?= $block->getUrl('fin_route/index/index/') ?>">
        <?= __("Go to Tablets records->") ?>
    </a>
<?php endif ?>