<?php
use Alex\Fin\Model\TabletsCasesModel;
/** @var \Alex\Fin\Block\TabletsCases $block */
/** @var \Alex\Fin\Model\ResourceModel\TabletsCases\Collection $tabletsCasesCollection */
$tabletsCasesCollection = $block->getTabletsCasesCollection();
$id = $block->getIdRequest(TabletsCasesModel::FORTABSKU);

/**
 * Форматування коду!
 * Відрефакторити action відповідно до того, що я описав у блоках
 * Видалити з use невикористовувані класи
 */
?>

<table class="data table" id="test-data-table">
    <caption class="table-caption">Test Data</caption>
    <thead>
    <tr>
        <th scope="col" class="col Entity">Entity ID</th>
        <th scope="col" class="col brand">BRAND</th>
        <th scope="col" class="col desc">Description</th>
        <th scope="col" class="col created_at">Created At</th>
        <th scope="col" class="col tabsku">TabSKU</th>
        <th scope="col" class="col casesku">caseSKU</th>
        <th scope="col" class="col price USD">Price USD</th>
        <th scope="col" class="col price UAH">Price UAH</th>
        <th scope="col" class="col cases">Color</th>
        <th scope="col" class="col delete">Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php if($tabletsCasesCollection) : ?>
    <?php foreach ($tabletsCasesCollection as $case): ?>
        <?php /** @var TabletsCasesModel $case */ ?>
    <tr>
            <td data-th="entity" class="col Entity"><?php echo $case->getId(); ?></td>
            <td data-th="brand" class="col brand"><?php echo $case->getBrand(); ?></td>
            <td data-th="description" class="col desc"><?php echo $case->getDescription(); ?></td>
            <td data-th="date" class="col created_at"><?php echo $case->getCreatedAt(); ?></td>
            <td data-th="sku" class="col tabSKU"><?php echo $case->getForTabSku(); ?></td>
            <td data-th="sku" class="col caseSKU"><?php echo $case->getCaseSku(); ?></td>
            <td data-th="price" class="col price USD"><?php echo $case->getPrice(); ?></td>
        <td data-th="price" class="col price UAH"><?php echo $case->getPrice()*$block->getExternalCurrency(); ?></td>
            <td data-th="color" class="col color"><?php echo $case->getColor(); ?></td>
        <td data-th="extra" class="col delete">
            <a href=" <?= $block->getUrl('fin_route/index/deletecase/',
                ['casesku' => $case->getCaseSku()]) ?>" class="action view">
                <span>DELETE THIS CASE!!!</span>
            </a>
    </tr>
         <?php endforeach; ?>
        <a class="sort" href=" <?= $block->getUrl('fin_route/index/cases',
            ['forTabSKU' =>$block->getIdRequest(TabletsCasesModel::FORTABSKU) ,
                'sort' => $block->getSortParam(TabletsCasesModel::SORT),
                'sortparam' =>'price']) ?>">
            <?= __("ASC/DESC by price sorting switch!")?></a>
    <br>
        <a class="sort" href=" <?= $block->getUrl('fin_route/index/cases',
            ['forTabSKU' =>$block->getIdRequest(TabletsCasesModel::FORTABSKU) ,
                'sort' => $block->getSortParam(TabletsCasesModel::SORT),
            'sortparam' =>'color']) ?>">
            <?= __("ASC/DESC by color sorting switch!")?></a>
    <br>
        <a class="sort" href=" <?= $block->getUrl('fin_route/index/cases',
            ['forTabSKU' =>$block->getIdRequest(TabletsCasesModel::FORTABSKU) ,
                'sort' => $block->getSortParam(TabletsCasesModel::SORT),
                'sortparam' =>'casesku']) ?>">
            <?= __("ASC/DESC by caseSKU sorting switch!")?></a>
    <?php endif ?>
    <?php if (!$tabletsCasesCollection) : ?>
        <h3 class="my block">Cases for tablet with ID <?= $id ?> is not created YET!</h3>
    <?php endif ?>
        </tbody>
</table>
<?php if ($id !=0): ?>
    <a class="show" href=" <?= $block->getUrl('fin_route/index/cases/forTabSKU/0') ?>">
        <?= __("Show All avaible Cases (for ALL tablets!) ->")?></a>
    <br>
    <a class="new" href=" <?= $block->getUrl('fin_route/index/newcase',
        ['fortabsku' => $id]) ?>">
        <?= __("Press to create a new case for this tablet!")?></a>
<?php endif ?>
<br>
<a class="go_back" href=" <?= $block->getUrl('fin_route/index/index/') ?>">
    <?= __("Go to Tablets records->")?></a>