<?php
use Alex\Fin\Model\TabletsModel;
use Alex\Fin\Api\Data\TabletsInterface;
use Alex\Fin\Block\Tablets;
/** @var \Alex\Fin\Block\Tablets $block */
/** @var \Alex\Fin\Model\ResourceModel\Tablets\Collection $tabletsCollection */
$tabletsCollection = $block->getTabletsCollection();
$count = 0;
$quantity = $block->getQuantity();

/**
 * Форматування коду!
 * Відрефакторити action відповідно до того, що я описав у блоках
 * Видалити з use невикористовувані класи
 */
?>
<a class="sort" href=" <?= $block->getUrl('fin_route/index/index',
    ['sort' => $block->getSortParam()]) ?>">
    <?= __("ASC/DESC by price sorting switch!")?></a>
<table class="data table" id="test-data-table">
    <caption class="table-caption">Test Data</caption>
    <thead>
    <tr>
        <th scope="col" class="col Entity">Entity ID</th>
        <th scope="col" class="col brand">BRAND</th>
        <th scope="col" class="col desc">Descriptions</th>
        <th scope="col" class="col created_at">Created At</th>
        <th scope="col" class="col sku">SKU</th>
        <th scope="col" class="col model">Model</th>
        <th scope="col" class="col price">Price</th>
        <th scope="col" class="col quant">Cases Quantity</th>
        <th scope="col" class="col cases">Cases Details</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($tabletsCollection as $tablet): ?>
    <?php /** @var TabletsModel $tablet */ ?>
        <?php if ($count == $quantity): ?>
            <h1 class="message"><?= __("Only $quantity records is shown according to system settings!") ?></h1>
            <a class="read-more" href=" <?= $block->getUrl('fin_route/pendex/index/') ?>">
                <?= __("To show ALL tablets Recodrs!")?></a>
            <?php break 1; ?>
        <?php endif ?>
        <tr>
            <td data-th="Entity" class="col Entity"><?php echo $tablet->getId(); ?></td>
            <td data-th="id" class="col brand"><?php echo $tablet->getBrand(); ?></td>
            <td data-th="descriptions" class="col desc"><?php echo $tablet->getDescriptions(); ?></td>
            <td data-th="date" class="col created_at"><?php echo $tablet->getCreatedAt(); ?></td>
            <td data-th="sku" class="col sku"><?php echo $tablet->getTabSku(); ?></td>
            <td data-th="model" class="col model"><?php echo $tablet->getModel(); ?></td>
            <td data-th="price" class="col price"><?php echo $tablet->getPrice(); ?></td>
            <td data-th="quant" class="col quant"><?php echo $block->getCasesQunatity($tablet->getTabSku()); ?></td>
            <td data-th="extra" class="col cases">
                <a href=" <?= $block->getUrl('fin_route/index/cases',
                    ['forTabSKU' => $tablet->getTabSku(), 'sort' => '0', 'sortparam' =>'price']) ?>" class="action view">
                    <span>View Cases Menu</span>
                </a>
        </tr>
        <?php $count++ ?>
    <?php endforeach; ?>
    </tbody>
</table>
<a class="new" href=" <?= $block->getUrl('fin_route/index/newtablet') ?>">
    <?= __("Press to create a new tablet!")?></a>