<?php

/**
 * Рекомендації:
 *
 * Всі класи/інтерфейси в use повинні бути відсортованими по алфавіту.
 * Всі невикористовувані в коді класи повинні бути видаленими з use.
 */
use Owner\TaskModul\Block\Cars;
use Owner\TaskModul\Model\CarModel;
use Owner\TaskModul\ViewModel\AdditionInfo;
use Owner\TaskModul\Model\ResourceModel\Car\Collection as CarCollection;

use Owner\TaskModul\Model\EngineModel;

/**
 * @var CarCollection $cars
 * @var Cars $block
 */
$cars = $block->getCars();

/** @var AdditionInfo $viewModel */
$viewModel = $block->getData('addition_viewModel');
/**
 * Рекомендації:
 *
 * Відформатувати код нижче:
 *
 * 1. Видалити непотрібні пусті рядки
 * 2. Текст (там де це можливо) огорнути в Phrase об'єкт: __('');
 */
?>

<div class="container">
    <h1>
        <?= __('Sorting type: %1', $viewModel->useSort()) ?>
    </h1>

    <?php if ($cars): ?>
        <p class="link">
            <a class="go-back"
               href="<?= $block->getUrl('route_last') ?>">
                Go back
            </a>
        </p>
        <?php foreach ($cars as $item): ?>

            <?php
            /**
             * @var CarModel  $item
             * @var EngineModel  $engine
             */
            ?>


            <div class="car-id-<?= $item->getId() ?>">

                <h4 class="name">
                    <?= __('Brand: %1', $item->getBrand()) ?>
                </h4>

                <h4 class="user_id">
                    <?= __('Model: %1', $item->getModel()) ?>
                </h4>

                <h4 class="description" style="color: red">
                    <?php
                    /**
                     * В даному методі може бути викинуте виключення, рекомендації:
                     *
                     * 1. Огорнути в try/catch при цьому дотримуючись повернення правильного
                     * типу даних
                     */
                    $engine = $block->getById($item->getEngineId());
                    ?>
                    <?= __('Engine: %1', $engine->getWin()) ?>
                </h4>

                <h4 class="price">
                    <?= __('Price: %1', $item->getPrice())  ?>
                </h4>

                <h4 class="price">
                    <?= __('Years: %1', $item->getYears())  ?>
                </h4>

                <h5 class="created_at">
                    <?= __('Created at: %1', $item->getCreatedAt()) ?>
                </h5>
            </div>
            <hr><br>
        <?php endforeach; ?>
    <?php else: ?>
        <div>
            <p>List of cars is empty</p>
        </div>
        <p class="link">
            <a class="go-back"
               href="<?= $block->getUrl('route_last') ?>">
                Go back
            </a>
        </p>
    <?php endif; ?>
</div>

