<?php

use Owner\TaskModul\Block\Cars;
use Owner\TaskModul\Model\CarModel;
use Owner\TaskModul\ViewModel\AdditionInfo;
use Owner\TaskModul\Model\ResourceModel\Car\Collection as CarCollection;
use Owner\TaskModul\Model\EngineModel;

/**
 * @var CarCollection $cars
 * @var Cars $block
 */
$cars = $block->getCars();

/** @var AdditionInfo $viewModel */
$viewModel = $block->getData('addition_viewModel');

/** size of display items */
$number_element = 0;

/** $engineId for return to car list of engine */
$request = $this->getRequest();
$engineId = (int)$request->getParam('engine_id');
?>
<div class="container">
    <?php if ($cars !== null): ?>
        <table>
        <thead>
        <tr class="border-style thead-style">
            <th scope="col"><?= __('Entity id') ?></th>
            <th scope="col"><?= __('Brand') ?></th>
            <th scope="col"><?= __('Model') ?></th>
            <th scope="col"><?= __('Engine') ?></th>
            <th scope="col"><?= __('Price') ?></th>
            <th scope="col"><?= __('Years') ?></th>
            <th scope="col"><?= __('Created at') ?></th>
            <th scope="col"><?= __('Actions') ?></th>
        </tr>
        </thead>
        <tbody>
            <p class="link" style="margin-bottom: 15px;">
                <a class="go-back"
                   href="<?= $block->getUrl('route_last') ?>">
                    <?= __('Go back') ?>
                </a>
            </p>
            <?php foreach ($cars as $item): ?>
                <?php

                if ($viewModel->getAdminSetting() === 1 &&
                    $number_element == $viewModel->getNumberRecord()
                ) {
                    continue;
                }

                $number_element++;

                /**
                 * @var CarModel $item
                 * @var EngineModel $engine
                 */
                ?>
                <tr class="engine-row border-style" id="carId-<?= $item->getId() ?>">
                    <th><?= $item->getId() ?></th>
                    <th><?= $item->getBrand() ?></th>
                    <th><?= $item->getModel() ?></th>

                    <?php $engine = $block->getById($item->getEngineId()); ?>

                    <?php if ($engine && $engine->getId()): ?>
                        <th style="color: red"><?= $engine->getWin() ?></th>
                    <?php else: ?>
                        <th style="color: red"><?= __('There are some error with engines!') ?></th>
                    <?php endif; ?>

                    <th><?= $item->getPrice() ?></th>
                    <th><?= $item->getYears() ?></th>
                    <th><?= $item->getCreatedAt() ?></th>
                    <th>
                        <a class="engine-delete" style="margin-right: 15px; font-size: large; color: red"
                           href="<?= $block->getUrl('route_last/index/deletecar',
                               [
                                   'carId' => $item->getId(),
                                   'engineId' => $engineId
                               ]) ?>">X</a>
                    </th>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php else: ?>
        <div>
            <h1 style="color: red;">
                <?= __('List of cars is empty') ?>
            </h1>
        </div>
        <p class="link">
            <a class="go-back"
               href="<?= $block->getUrl('route_last') ?>">
                <?= __('Go back') ?>
            </a>
        </p>
    <?php endif; ?>
</div>

