<?php

use Owner\TaskModul\Model\EngineModel;
use Owner\TaskModul\ViewModel\AdditionInfo;

/**
 * @var Owner\TaskModul\Model\ResourceModel\Engine\Collection $engines
 * @var Owner\TaskModul\Block\Engines $block
 */
$engines = $block->getEngines();

/** @var AdditionInfo $viewModel */
$viewModel = $block->getData('addition_viewModel');

/** Count of Engine columns */
$engineColumns = $viewModel->getEngineColumn();

/** size of display items */
$number_element = 0;
?>
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <form method="get" action="<?= $block->useFilter() ?>">
                <label for="sortField"><?= __('Choose field for sort:') ?></label>
                <select id="sortField" name="sortField">
                    <?php foreach ($engineColumns as $key => $field): ?>
                        <option  value="<?= $key ?>"><?= __($field) ?></option>
                    <?php endforeach; ?>
                </select>
                <label for="sortType"><?= __('Sort type:') ?></label>
                <select id="sortType" name="sortType">
                    <option value="ASC"><?= __('ASC') ?></option>
                    <option value="DESC"><?= __('DESC') ?></option>
                </select>
                <?php if($viewModel->getAdminSetting() === 0): ?>
                    <button  type="submit"><?= __('Use filter') ?></button>
                <?php else: ?>
                    <p style="color: red; font-size: small; margin: 15px"><?= __('Using admin setting filter!')?></p>
                <?php endif; ?>
            </form>
        </div>
    </div>

    <?php if($engines): ?>
        <table>
            <thead>
                <tr class="border-style thead-style">
                    <th scope="col"><?= __('Entity id') ?></th>
                    <th scope="col"><?= __('Manufacturer') ?></th>
                    <th scope="col"><?= __('Win') ?></th>
                    <th scope="col"><?= __('Power') ?></th>
                    <th scope="col"><?= __('Volume') ?></th>
                    <th scope="col"><?= __('Years') ?></th>
                    <th scope="col"><?= __('Created at' )?></th>
                    <th scope="col"><?= __('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($engines as $item): ?>
                    <?php
                    if ($viewModel->getAdminSetting() === 1 &&
                        $number_element == $viewModel->getNumberRecord()
                    ) {
                        continue;
                    }

                    $number_element++;

                    /**
                     * @var EngineModel  $item
                     */
                    ?>
                <tr class="engine-row border-style" id="carId-<?= $item->getId() ?>"
                    onclick="document.location.href  = '<?= $block->getUrl('route_last/index/car',
                        ['engine_id' => $item->getId()])?>' ">
                    <th><?= $item->getId() ?></th>
                    <th><?= $item->getManufacturer() ?></th>
                    <th><?= $item->getWin() ?></th>
                    <th><?= $item->getPower() ?></th>
                    <th><?= $item->getVolume() ?></th>
                    <th><?= $item->getYears() ?></th>
                    <th><?= $item->getCreatedAt() ?></th>
                    <th>
                        <a class="engine-delete" style="margin-right: 15px; font-size: large; color: red"
                            href="<?= $block->getUrl('route_last/index/deleteengine',
                                ['_current' => true,
                                '_query' =>
                                    [
                                        'engine_id' => $item->getId()
                                    ]
                                ])?>">X</a>
                    </th>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <div>
            <h1 style="color: red;">
                <?= __('List of engines is empty') ?>
            </h1>
        </div>
    <?php endif; ?>
</div>

